services:
  - type: web
    name: dealdrip
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn app:app"
    plan: free
    autoDeploy: false
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.10
      - key: NODE_VERSION  
        value: 18.18.0

databases:
  - name: dealdrip-postgres
    plan: free